# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  azureSubscriptionEndpoint: "Service Connection Name"
  azureContainerRegistry: iotedgetainer.azurecr.io

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Azure IoT!
  displayName: 'Run a Edgebuild and upload script'

- task: AzureIoTEdge@2
  inputs:
    action: 'Build module images'
    templateFilePath: 'EdgeDemo/deployment.template.json'
    defaultPlatform: 'amd64'

- task: AzureIoTEdge@2
  displayName: AzureIoTEdge - Push module images
  inputs:
    action: Push module images
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: '{"loginServer":"$(azureContainerRegistry)"}'
    templateFilePath: EdgeDemo/deployment.template.json
    defaultPlatform: amd64
    fillRegistryCredential: "true"
